#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaxiOnline.Android.Resource", IsApplication=true)]

namespace TaxiOnline.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OsmSharp.Android.UI.Resource.String.library_name = global::TaxiOnline.Android.Resource.String.library_name;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.ApplicationName = global::TaxiOnline.Android.Resource.String.ApplicationName;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.Hello = global::TaxiOnline.Android.Resource.String.Hello;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.library_name = global::TaxiOnline.Android.Resource.String.library_name;
			global::TaxiOnline.ClientInfrastructure.Android.Resource.String.ApplicationName = global::TaxiOnline.Android.Resource.String.ApplicationName;
			global::TaxiOnline.ClientInfrastructure.Android.Resource.String.Hello = global::TaxiOnline.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DriverIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PedestrianIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RefreshIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SearchIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SettingsIcon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050028
			public const int applySettingsButton = 2131034152;
			
			// aapt resource value: 0x7f050018
			public const int callToDriverButton = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int cancelMessageToDriverButton = 2131034138;
			
			// aapt resource value: 0x7f050026
			public const int cancelRegistrationButton = 2131034150;
			
			// aapt resource value: 0x7f05002a
			public const int cancelSettingsButton = 2131034154;
			
			// aapt resource value: 0x7f050021
			public const int carBrandEditText = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int carColorEditText = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int carNumberEditText = 2131034146;
			
			// aapt resource value: 0x7f050013
			public const int chooseCityButton = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int cityNameTextView = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int cityTextView = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int confirmPedestrianRequestButton = 2131034127;
			
			// aapt resource value: 0x7f050025
			public const int confirmRegistrationButton = 2131034149;
			
			// aapt resource value: 0x7f050002
			public const int connectionStateImageView = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int driverIconImageView = 2131034118;
			
			// aapt resource value: 0x7f050024
			public const int driverPhoneNumberEditText = 2131034148;
			
			// aapt resource value: 0x7f050009
			public const int driverPopupCarBrandTextView = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int driverPopupCarColorTextView = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int driverPopupCarNumberTextView = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int driverPopupPersonNameTextView = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int driverPopupPhoneNumberTextView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int driverPopupSkypeNumberTextView = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int driverProfileView = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int driverRadioButton = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int driverResponsesListView = 2131034129;
			
			// aapt resource value: 0x7f050023
			public const int driverSkypeNumberEditText = 2131034147;
			
			// aapt resource value: 0x7f050014
			public const int mapLayout = 2131034132;
			
			// aapt resource value: 0x7f05001e
			public const int pedestrianPhoneNumberEditText = 2131034142;
			
			// aapt resource value: 0x7f050017
			public const int pedestrianProfileView = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int pedestrianRadioButton = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int pedestrianRequestLayout = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int pedestrianRequestTextView = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int pedestrianSkypeNumberEditText = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int personNameEditText = 2131034143;
			
			// aapt resource value: 0x7f050003
			public const int personsView = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int quickCallToDriverButton = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int refreshCitiesButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int registerButton = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int rejectPedestrianRequestButton = 2131034128;
			
			// aapt resource value: 0x7f050029
			public const int restartApplicationForSettingsButton = 2131034153;
			
			// aapt resource value: 0x7f050019
			public const int sendMessageToDriverButton = 2131034137;
			
			// aapt resource value: 0x7f050027
			public const int serverAddressEditText = 2131034151;
			
			// aapt resource value: 0x7f050000
			public const int settingsButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBarLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuthenticationLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CityInfoLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DriverInfoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DriverPopupDetailsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DriverProfileLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DriverProfileResponseLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DriverReducedInfoLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DriverResponseLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DriverResponsesLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int DriverSelfInfoLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MainLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int maplayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PedestrianInfoLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PedestrianPopupDetailsLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PedestrianProfileLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PedestrianProfileRequestLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PedestrianReducedInfoLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PedestrianSelfInfoLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int RegistrationLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SettingsLayout = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Apply = 2130968580;
			
			// aapt resource value: 0x7f04001a
			public const int AuthenticationFailed = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int AuthorizingMessage = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int AuthorizingTitle = 2130968600;
			
			// aapt resource value: 0x7f040020
			public const int CallToDriver = 2130968608;
			
			// aapt resource value: 0x7f040005
			public const int Cancel = 2130968581;
			
			// aapt resource value: 0x7f040023
			public const int CancelMessageToDriver = 2130968611;
			
			// aapt resource value: 0x7f040016
			public const int CarBrand = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int CarColor = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int CarNumber = 2130968599;
			
			// aapt resource value: 0x7f04000a
			public const int ChooseCityToolTip = 2130968586;
			
			// aapt resource value: 0x7f040025
			public const int ConfirmPedestrianRequest = 2130968613;
			
			// aapt resource value: 0x7f040009
			public const int ConnectToServerFailed = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int ConnectingToServerMessage = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int ConnectingToServerTitle = 2130968583;
			
			// aapt resource value: 0x7f040011
			public const int Driver = 2130968593;
			
			// aapt resource value: 0x7f04001e
			public const int FailedToEnumrateDrivers = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int FailedToEnumratePedestrians = 2130968607;
			
			// aapt resource value: 0x7f040024
			public const int FailedToInitRequest = 2130968612;
			
			// aapt resource value: 0x7f04000c
			public const int FailedToLoadPersons = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04001d
			public const int LoadDataMessage = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int LoadTitle = 2130968604;
			
			// aapt resource value: 0x7f04000b
			public const int NoCityFound = 2130968587;
			
			// aapt resource value: 0x7f04001b
			public const int NoLocationServiceAvailable = 2130968603;
			
			// aapt resource value: 0x7f04000d
			public const int NoParticipationRole = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int Pedestrian = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int PersonName = 2130968596;
			
			// aapt resource value: 0x7f040021
			public const int PhoneCallError = 2130968609;
			
			// aapt resource value: 0x7f040013
			public const int PhoneNumber = 2130968595;
			
			// aapt resource value: 0x7f04000f
			public const int Register = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int Registration = 2130968590;
			
			// aapt resource value: 0x7f040026
			public const int RejectPedestrianRequest = 2130968614;
			
			// aapt resource value: 0x7f040006
			public const int Restart = 2130968582;
			
			// aapt resource value: 0x7f040022
			public const int SendMessageToDriver = 2130968610;
			
			// aapt resource value: 0x7f040003
			public const int ServerAddress = 2130968579;
			
			// aapt resource value: 0x7f040012
			public const int SkypeNumber = 2130968594;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
