#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaxiOnline.Android.Resource", IsApplication=true)]

namespace TaxiOnline.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OsmSharp.Android.UI.Resource.String.library_name = global::TaxiOnline.Android.Resource.String.library_name;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.ApplicationName = global::TaxiOnline.Android.Resource.String.ApplicationName;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.Hello = global::TaxiOnline.Android.Resource.String.Hello;
			global::TaxiOnline.ClientAdapters.Android.Resource.String.library_name = global::TaxiOnline.Android.Resource.String.library_name;
			global::TaxiOnline.ClientInfrastructure.Android.Resource.String.ApplicationName = global::TaxiOnline.Android.Resource.String.ApplicationName;
			global::TaxiOnline.ClientInfrastructure.Android.Resource.String.Hello = global::TaxiOnline.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DriverIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PedestrianIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RefreshIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SearchIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int cancelRegistrationButton = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int carColorEditText = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int chooseCityButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int cityNameTextView = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cityTextView = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int confirmRegistrationButton = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int connectionStateImageView = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int driverPhoneNumberEditText = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int driverRadioButton = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int driverSkypeNumberEditText = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int mapLayout = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int pedestrianPhoneNumberEditText = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int pedestrianRadioButton = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int pedestrianSkypeNumberEditText = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int personsView = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int refreshCitiesButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int registerButton = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBarLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuthenticationLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CityInfoLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DriverInfoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DriverProfileLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DriverReducedInfoLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DriverSelfInfoLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int maplayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PedestrianInfoLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PedestrianReducedInfoLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PedestrianSelfInfoLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RegistrationLayout = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040013
			public const int AuthenticationFailed = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int AuthorizingMessage = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int AuthorizingTitle = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int Cancel = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int CarColor = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int ChooseCityToolTip = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int ConnectToServerFailed = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ConnectingToServerMessage = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int ConnectingToServerTitle = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int Driver = 2130968589;
			
			// aapt resource value: 0x7f040016
			public const int FailedToEnumratePedestrians = 2130968598;
			
			// aapt resource value: 0x7f040008
			public const int FailedToLoadPersons = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040015
			public const int LoadDataMessage = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int LoadTitle = 2130968596;
			
			// aapt resource value: 0x7f040007
			public const int NoCityFound = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int NoParticipationRole = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Pedestrian = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int PhoneNumber = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int Register = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int SkypeNumber = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
