USE [master]
GO

/****** Object:  Database [TaxiOnline]    Script Date: 20.04.2014 11:00:04 ******/
CREATE DATABASE [TaxiOnline]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaxiOnline', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TaxiOnline.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TaxiOnline_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TaxiOnline_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TaxiOnline] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaxiOnline].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaxiOnline] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaxiOnline] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaxiOnline] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaxiOnline] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaxiOnline] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaxiOnline] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaxiOnline] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TaxiOnline] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaxiOnline] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaxiOnline] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaxiOnline] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaxiOnline] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaxiOnline] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaxiOnline] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaxiOnline] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaxiOnline] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaxiOnline] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaxiOnline] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaxiOnline] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaxiOnline] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaxiOnline] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaxiOnline] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaxiOnline] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaxiOnline] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaxiOnline] SET  MULTI_USER 
GO

ALTER DATABASE [TaxiOnline] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaxiOnline] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaxiOnline] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaxiOnline] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TaxiOnline] SET  READ_WRITE 
GO

USE [TaxiOnline]
GO

/****** Object:  Table [dbo].[Cities]    Script Date: 20.04.2014 11:01:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cities](
	[Id] [uniqueidentifier] NOT NULL,
	[InitialLatitude] [float] NOT NULL,
	[InitialLongitude] [float] NOT NULL,
	[InitialZoom] [float] NOT NULL,
 CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Cities] ADD  CONSTRAINT [DF_Cities_Id]  DEFAULT (newid()) FOR [Id]
GO

USE [TaxiOnline]
GO

/****** Object:  Table [dbo].[CityNames]    Script Date: 20.04.2014 11:01:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CityNames](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](100) NULL,
	[CultureName] [nvarchar](8) NULL,
	[CityId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CityNames] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

